#ifndef DIRECTORYVIEWEXTENSIONSPLUGIN1TEST_GLOBAL_H
#define DIRECTORYVIEWEXTENSIONSPLUGIN1TEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIRECTORYVIEWEXTENSIONSPLUGIN1TEST_LIBRARY)
#  define DIRECTORYVIEWEXTENSIONSPLUGIN1TESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIRECTORYVIEWEXTENSIONSPLUGIN1TESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIRECTORYVIEWEXTENSIONSPLUGIN1TEST_GLOBAL_H
