name: CI

on:
  schedule:
    - cron: "0 2 * * 1-5"
  push:
    branches:
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    name: build test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt update | 
      sudo apt -y install libglib2.0-dev qt5-default libqt5x11extras5-dev libgsettings-qt-dev
    - name: Build & Test
      run: |
        qmake .
        make
        sudo make install
        #/usr/bin/peony-qt -h
        #/usr/bin/peony-qt-desktop -h
